// Hungarian product names, keyed by product ID (the same IDs used in prices.xlsx
// and catalog.mjs). Used to label the price sheet so Hungarian-speaking
// colleagues can read it. Editing these does NOT affect the website — the site
// takes its names from catalog.mjs; the spreadsheet's Product column is only a
// human-friendly label.
export const HU_NAMES = {
  "round-bench": "Kerek pad",
  "bench-bl01": "Pad",
  "bench-ic01": "Pad",
  "bench-mi01": "Pad",
  "bench-st01": "Pad",
  "bench-mi02": "Pad",
  "bench-ic02": "Pad",
  "bench-planter": "Pad virágládával",
  "bench-bike-rack": "Pad kerékpártartóval",
  "bench-carved": "Pad",
  "waste-basket-ib01": "Szemetes",
  "waste-basket-1880": "Szemetes",
  "waste-basket-1400": "Szemetes",
  "waste-basket-2490": "Szemetes",
  "carved-flower-box-lj03": "Faragott virágláda",
  "flower-box-lj01": "Virágláda",
  "water-wheel-well": "Kerekeskút",
  "garden-daybed": "Kerti napozóágy",
  "round-bench-table": "Kerek pad és asztal",
  "table-icm01": "Asztal",
  "chess-table": "Sakkasztal két paddal",
  "bus-stop-bm02": "Buszmegálló",
  "bus-stop-bm01": "Buszmegálló",
  "szekely-gate": "Székelykapu",
  "octagonal-pavilion": "Nyolcszögletű pavilon",
  "solid-wood-fence": "Tömörfa kerítés",
  "information-board": "Információs tábla",
  "bike-rack-bt01": "Kerékpártartó",
  "swing-frame-lp02": "Mérleghinta",
  "swing-frame-lp01": "Mérleghinta",
  "swing": "Hinta",
  "childrens-swing": "Gyermekhinta",
  "large-swing": "Nagy hinta",
  "hexagonal-sandpit": "Hatszögletű homokozó",
  "balance-beam": "Egyensúlyozó kígyó",
  "hexagonal-climbing": "Hatszögletű mászóka",
  "small-boat": "Kishajó",
  "airplane-curved": "Rugós repülő",
  "sensory-maze": "Szenzomotoros fejlesztő labirintusjáték",
  "airplane-ap01": "Repülő",
  "mini-playground": "Mini vár típusú játszókomplexum",
  "two-seat-swing-tw02": "Dupla tömörfa hintaállvány torony típusú csúszdával",
  "two-seat-swing-tw03": "Dupla tömörfa hintaállvány csúszdával",
  "steamboat-karibi": "Karibi hajó",
  "rustic-two-seat-swing": "Rusztikus dupla tömörfa hinta",
  "carousel": "Körhinta",
  "rustic-swing-roof": "Rusztikus tömörfa hinta tetővel",
  "solid-wood-bell": "Tömörfa harangláb",
};

// Hungarian column headers for the price sheet (order matches the columns).
export const HU_HEADERS = [
  "Azonosító (ne szerkeszd)",
  "Termék",
  "Változat / Méret",
  "Ár (lei)",
  "Mértékegység",
  "Megjegyzés",
];
